#eureka:
#  server:
#    enableSelfPreservation: false  # Disable self-preservation mode (optional)
#
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/  # Point to your local Eureka server
#  instance:
#    hostname: ${HOSTNAME:localhost}  # Dynamic hostname (optional)
#    metadataMap:
#      zone: default
#
#server:
#  port: 8761

spring:
  application:
    name: CustomerService

  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password:
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 9097

